// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT05Obhfcm68s3eDsR2viADU3vNSYTaSw',
    appId: '1:244429682406:web:c6264a9b7679dea7416d27',
    messagingSenderId: '244429682406',
    projectId: 'bionicproject1',
    authDomain: 'bionicproject1.firebaseapp.com',
    storageBucket: 'bionicproject1.appspot.com',
    measurementId: 'G-XW65M42XZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQg3324VNGMt30oq26-uXpOaGar5tYWUc',
    appId: '1:244429682406:android:b2cdb0f1a74c2d4f416d27',
    messagingSenderId: '244429682406',
    projectId: 'bionicproject1',
    storageBucket: 'bionicproject1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdEHgNQi7KvPApLmJamuAcgtZptvQhac',
    appId: '1:244429682406:ios:414114c360b7535f416d27',
    messagingSenderId: '244429682406',
    projectId: 'bionicproject1',
    storageBucket: 'bionicproject1.appspot.com',
    iosClientId: '244429682406-hu2lfqmam563ckrclq8fdv8115nk460u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bionicTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCdEHgNQi7KvPApLmJamuAcgtZptvQhac',
    appId: '1:244429682406:ios:414114c360b7535f416d27',
    messagingSenderId: '244429682406',
    projectId: 'bionicproject1',
    storageBucket: 'bionicproject1.appspot.com',
    iosClientId: '244429682406-hu2lfqmam563ckrclq8fdv8115nk460u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bionicTest',
  );
}
